name: PTC
version: '${project.version}'
main: org.kayteam.ptc.PTC
api-version: 1.18
authors: [ KayTeam ]
website: https://kayteam.org
depend: [ PlaceholderAPI, TAB]
commands:
  ptc:
    description: PTC main command
  arena:
    description: Arena main command
  test:
    description: test
