defaultGameDuration: 3600
initialCoreLives: 10
cooldownMaterials:
  STONE: 10
  COAL_ORE: 20
  IRON_ORE: 30
  LAPIS_ORE: 30
  GOLD_ORE: 40
  DIAMOND_ORE: 50
chatFormat:
  default: "&7%vault_prefix%%player_name%&7: &f%message%"
  inGameGlobal: "&8[&7%teamColour%] &7%player_name%&8: &f%message%"
  inGameTeam: "&8[&7TEAM&8] &7%player_name%&8: &f%message%"